services:
  dvc-init:
    build:
      context: .
      dockerfile: buildfiles/dvc-init.Dockerfile
    container_name: dvc-init
    volumes:
      - ./models:/app/models
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - PYTHONUNBUFFERED=1
    networks:
      - dna-api-network

  api-catboost:
    build:
      context: .
      dockerfile: buildfiles/api.Dockerfile
    container_name: dna-api-catboost
    ports:
      - "8001:8000"
    environment:
      - MODEL_VERSION=catboost
      - API_NAME=catboost-api
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    volumes:
      - ./api/config-catboost.json:/app/api/config.json:ro
      - ./models:/app/models:ro
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    depends_on:
      dvc-init:
        condition: service_completed_successfully
    networks:
      - dna-api-network

  api-lightgbm:
    build:
      context: .
      dockerfile: buildfiles/api.Dockerfile
    container_name: dna-api-lightgbm
    ports:
      - "8002:8000"
    environment:
      - MODEL_VERSION=lgbm
      - API_NAME=lightgbm-api
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    volumes:
      - ./api/config-lgbm.json:/app/api/config.json:ro
      - ./models:/app/models:ro
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    depends_on:
      dvc-init:
        condition: service_completed_successfully
    networks:
      - dna-api-network

  api-random-forest:
    build:
      context: .
      dockerfile: buildfiles/api.Dockerfile
    container_name: dna-api-rf
    ports:
      - "8003:8000"
    environment:
      - MODEL_VERSION=rf
      - API_NAME=random-forest-api
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    volumes:
      - ./api/config-rf.json:/app/api/config.json:ro
      - ./models:/app/models:ro
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    depends_on:
      dvc-init:
        condition: service_completed_successfully
    networks:
      - dna-api-network

  prometheus:
    image: prom/prometheus:latest
    container_name: dna-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    restart: unless-stopped
    depends_on:
      - api-catboost
      - api-lightgbm
      - api-random-forest
    networks:
      - dna-api-network

  grafana:
    image: grafana/grafana:latest
    container_name: dna-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana_data:/var/lib/grafana
    restart: unless-stopped
    depends_on:
      - prometheus
    networks:
      - dna-api-network

networks:
  dna-api-network:
    driver: bridge

volumes:
  prometheus_data:
  grafana_data: 