stages:
  process:
    cmd: python src/process.py
    deps:
      - src/process.py
      - data/embeddings
    outs:
      - data/processed_embeddings

  train_lightgbm:
    cmd: python src/train.py --model lightgbm --depth 8 --lr=0.05 --iterations 300 --out_suffix lgbm
    deps:
      - src/train.py
      - data/processed_embeddings
    outs:
      - models/lgbm

  train_random_forest:
    cmd: python src/train.py --model random_forest --depth 6 --iterations 300 --out_suffix rf
    deps:
      - src/train.py
      - data/processed_embeddings
    outs:
      - models/rf
      
  train_catboost:
    cmd: python src/train.py --model catboost --depth 4 --lr 0.02 --out_suffix catboost
    deps:
      - src/train.py
      - data/processed_embeddings
    outs:
      - models/catboost

  evaluate:
    cmd: python src/evaluate.py
    deps:
      - src/evaluate.py
      - models/catboost
      - models/rf
      - models/lgbm
      - data/processed_embeddings
    outs:
      - mlflow_metrics
